language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - mvn -B versions:set -DnewVersion=$TRAVIS_BRANCH
script:
  - mvn -B package
  - docker build -t inseefrlab/bootcampjs-api .
deploy:
  skip_cleanup: true
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push inseefrlab/bootcampjs-api
  on:
    branch: 1-ci
